<?php

namespace App;

class CONSTANT

{
    const ARR_BOTS = [
        ['name'=>"Big",'rating'=>198,'email'=>'1'],
        ['name'=>"Эмиль",'rating'=>135,'email'=>'2'],
        ['name'=>"Danila",'rating'=>67,'email'=>'3'],
        ['name'=>"Alexandr",'rating'=>165,'email'=>'4'],
        ['name'=>"Igor",'rating'=>298,'email'=>'5'],
        ['name'=>"Андрей",'rating'=>435,'email'=>'6'],
        ['name'=>"Сергей",'rating'=>24,'email'=>'7'],
        ['name'=>"Марлен",'rating'=>132,'email'=>'8'],
        ['name'=>"Иван",'rating'=>213,'email'=>'9'],
        ['name'=>"Rustam",'rating'=>345,'email'=>'10'],
        ['name'=>"Николай",'rating'=>421,'email'=>'11'],
        ['name'=>"Daniil",'rating'=>68,'email'=>'12'],
        ['name'=>"Лада",'rating'=>173,'email'=>'13'],
        ['name'=>"Kost",'rating'=>298,'email'=>'14'],
        ['name'=>"Александр",'rating'=>354,'email'=>'15'],
        ['name'=>"Типо",'rating'=>490,'email'=>'16'],
        ['name'=>"Евгений",'rating'=>42,'email'=>'17'],
        ['name'=>"никита",'rating'=>121,'email'=>'18'],
        ['name'=>"Гира",'rating'=>208,'email'=>'19'],
        ['name'=>"Руфан",'rating'=>321,'email'=>'20'],
        ['name'=>"Veronika",'rating'=>404,'email'=>'21'],
        ['name'=>"Никита",'rating'=>78,'email'=>'22'],
        ['name'=>"Ababa",'rating'=>167,'email'=>'23'],
        ['name'=>"Nemo",'rating'=>254,'email'=>'24'],
        ['name'=>"Kostin",'rating'=>397,'email'=>'25'],
        ['name'=>"Стас",'rating'=>458,'email'=>'26'],
        ['name'=>"Malybu",'rating'=>42,'email'=>'27'],
        ['name'=>"Илья",'rating'=>132,'email'=>'28'],
        ['name'=>"Rager",'rating'=>241,'email'=>'29'],
        ['name'=>"Семен",'rating'=>306,'email'=>'30'],
        ['name'=>"Тилон",'rating'=>432,'email'=>'31'],
        ['name'=>"Дима",'rating'=>16,'email'=>'32'],
        ['name'=>"Danya",'rating'=>122,'email'=>'33'],
        ['name'=>"Andrey",'rating'=>245,'email'=>'34'],
        ['name'=>"Kakadu",'rating'=>315,'email'=>'35'],
        ['name'=>"juzim",'rating'=>447,'email'=>'36'],
        ['name'=>"basta",'rating'=>87,'email'=>'37'],
        ['name'=>"Asad",'rating'=>165,'email'=>'38'],
        ['name'=>"Андрей",'rating'=>291,'email'=>'39'],
        ['name'=>"Рома",'rating'=>365,'email'=>'40'],
        ['name'=>"Alexander",'rating'=>478,'email'=>'41'],
        ['name'=>"kuster",'rating'=>29,'email'=>'42'],
        ['name'=>"Вова",'rating'=>143,'email'=>'43'],
        ['name'=>"Antis",'rating'=>262,'email'=>'44'],
        ['name'=>"Андрей",'rating'=>387,'email'=>'45'],
        ['name'=>"Иван",'rating'=>456,'email'=>'46'],
        ['name'=>"Владимир",'rating'=>43,'email'=>'47'],
        ['name'=>"Тимур",'rating'=>104,'email'=>'48'],
        ['name'=>"Диана",'rating'=>234,'email'=>'49'],
        ['name'=>"Максим",'rating'=>321,'email'=>'50'],
        ['name'=>"Алексей",'rating'=>432,'email'=>'51'],
        ['name'=>"Кристина",'rating'=>67,'email'=>'52'],
        ['name'=>"Камиль",'rating'=>189,'email'=>'53'],
        ['name'=>"Роман",'rating'=>254,'email'=>'54'],
        ['name'=>"Yura",'rating'=>390,'email'=>'55'],
        ['name'=>"Михаил",'rating'=>487,'email'=>'56'],
        ['name'=>"Typer",'rating'=>32,'email'=>'57'],
        ['name'=>"Артем",'rating'=>145,'email'=>'58'],
        ['name'=>"Валерий",'rating'=>231,'email'=>'59'],
        ['name'=>"Павел",'rating'=>309,'email'=>'60'],
        ['name'=>"Иван",'rating'=>432,'email'=>'61'],
        ['name'=>"Kronos",'rating'=>84,'email'=>'62'],
        ['name'=>"Коля",'rating'=>197,'email'=>'63'],
        ['name'=>"Александра",'rating'=>256,'email'=>'64'],
        ['name'=>"Ксения",'rating'=>365,'email'=>'65']
    ];

}
